### ISSUE TITLE
Issues receiving credentials

### ISSUE THREAD

**Issue by drbh** [uport-project/uport-credentials#173] opened 2019-05-11 15:05 UTC
**Describe the bug**
I cannot get my "diploma" at https://uportlandia.uport.me/university

I see the following errors in my console.
```
Access to fetch at 'https://gn80ai4ca2.execute-api.us-east-1.amazonaws.com/prod/api/verify_credentials' from origin 'https://uportlandia.uport.me' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

**To Reproduce**
1. Request a diploma credential

**Comment by schowdhuri** [comment] 2019-05-11 15:14
@drbh I am unable to reproduce this error (I am on MacOS, Chrome 73). It could be a transient network issue. Can you please try again, preferably in an incognito browser window?

**Comment by drbh** [comment] 2019-05-11 15:25
Huh interesting - just tried again in FireFox and it worked no problem! I was not in an in an incognito browser window btw.

Issue on:
```
Chrome 74.0.3729.131
```

No problem on:
```
FireFox Quantum 66.0.3
```

Thanks for the response

**Comment by schowdhuri** [comment] 2019-05-11 15:29
Good to know! It does appear to be a network issue. Private browsing/incognito window rules out browser extensions and cache. Please feel free to reach out if you continue to face this issue.

**Comment by mirceanis** [comment] 2019-05-16 19:19
I'm closing this. seems to have been a temporary connectivity issue

**Closed by mirceanis** 2019-05-16 19:19 UTC
